services:
  backend:
    build: .
    container_name: chatting-backend
    env_file:
      - .env
    ports:
      - "8002:8002"
    restart: unless-stopped 

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  